"""Add detections_json and corrections_json to upload

Revision ID: 4d12dd92e576
Revises: 2604fb0b994e
Create Date: 2026-03-22 11:14:13.984719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d12dd92e576'
down_revision = '2604fb0b994e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detections_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('corrections_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_column('corrections_json')
        batch_op.drop_column('detections_json')

    # ### end Alembic commands ###
